export const sementes = [
    {
        "id": "semente_mirtilo",
        "nome": "Mirtilo",
        "preco_compra": 20,
        "preco_venda": 70,
        "tempo_colheita_horas": 0.05,
        "xp": 1,
        "nivel_requerido": 1,
        "img": "semente_mirtilo",
        "img_pronta": "pronto_mirtilo",
        "escala": 0.73,
        "area": [4, 4],
        "origem": [0.5, 0.58],
        "tipo": "semente",
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples",
    },
    {
        "id": "semente_soja",
        "nome": "Soja",
        "preco_compra": 50,
        "preco_venda": 165,
        "tempo_colheita_horas": 48,
        "xp": 2,
        "nivel_requerido": 1,
        "img": "semente_soja",
        "img_pronta": "pronto_soja",
        "escala": 0.78,
        "area": [4, 4],
        "tipo": "semente",
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_abobora",
        "nome": "Abóbora",
        "preco_compra": 70,
        "preco_venda": 115,
        "tempo_colheita_horas": 36,
        "xp": 2,
        "nivel_requerido": 1,
        "img": "semente_abobora",
        "img_pronta": "pronto_abobora",
        "escala": 0.78,
        "area": [4, 4],
        "tipo": "semente",
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_abobora_moranga",
        "nome": "Abóbora Moranga",
        "preco_compra": 70,
        "preco_venda": 115,
        "tempo_colheita_horas": 36,
        "xp": 2,
        "nivel_requerido": 1,
        "escala": 0.78,
        "area": [4, 4],
        "img": "semente_abobora_moranga",
        "img_pronta": "pronto_abobora_moranga",
        "tipo": "semente",
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_pimentao",
        "nome": "Pimentão",
        "preco_compra": 30,
        "preco_venda": 125,
        "tempo_colheita_horas": 24,
        "xp": 2,
        "nivel_requerido": 1,
        "img": "semente_pimentao",
        "img_pronta": "pronto_pimentao",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_pimenta",
        "nome": "Pimenta",
        "preco_compra": 80,
        "preco_venda": 240,
        "tempo_colheita_horas": 48,
        "xp": 2,
        "nivel_requerido": 2,
        "img": "semente_pimenta",
        "img_pronta": "pronto_pimenta",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_cenoura",
        "nome": "Cenoura",
        "preco_compra": 65,
        "preco_venda": 140,
        "tempo_colheita_horas": 8,
        "xp": 1,
        "nivel_requerido": 3,
        "img": "semente_cenoura",
        "img_pronta": "pronto_cenoura",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_beterraba",
        "nome": "Beterraba",
        "preco_compra": 65,
        "preco_venda": 140,
        "tempo_colheita_horas": 8,
        "xp": 1,
        "nivel_requerido": 3,
        "img": "semente_beterraba",
        "img_pronta": "pronto_beterraba",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_arroz",
        "nome": "Arroz",
        "preco_compra": 140,
        "preco_venda": 400,
        "tempo_colheita_horas": 72,
        "xp": 2,
        "nivel_requerido": 4,
        "img": "semente_arroz",
        "img_pronta": "pronto_arroz",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_alagado_2"
    },
    {
        "id": "semente_rabanete",
        "nome": "Rabanete",
        "preco_compra": 140,
        "preco_venda": 400,
        "tempo_colheita_horas": 72,
        "xp": 2,
        "nivel_requerido": 4,
        "img": "semente_rabanete",
        "img_pronta": "pronto_rabanete",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_alcachofra",
        "nome": "Alcachofra",
        "preco_compra": 90,
        "preco_venda": 185,
        "tempo_colheita_horas": 12,
        "xp": 1,
        "nivel_requerido": 5,
        "img": "semente_alcachofra",
        "img_pronta": "pronto_alcachofra",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_abacaxi",
        "nome": "Abacaxi",
        "preco_compra": 40,
        "preco_venda": 95,
        "tempo_colheita_horas": 2,
        "xp": 1,
        "nivel_requerido": 6,
        "img": "semente_abacaxi",
        "img_pronta": "pronto_abacaxi",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_uva",
        "nome": "Uva",
        "preco_compra": 150,
        "preco_venda": 414,
        "tempo_colheita_horas": 36,
        "xp": 2,
        "nivel_requerido": 7,
        "img": "semente_uva",
        "img_pronta": "pronto_uva",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_berinjela",
        "nome": "Berinjela",
        "preco_compra": 150,
        "preco_venda": 398,
        "tempo_colheita_horas": 48,
        "xp": 2,
        "nivel_requerido": 8,
        "img": "semente_berinjela",
        "img_pronta": "pronto_berinjela",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_trigo",
        "nome": "Trigo",
        "preco_compra": 140,
        "preco_venda": 321,
        "tempo_colheita_horas": 24,
        "xp": 2,
        "nivel_requerido": 9,
        "img": "semente_trigo",
        "img_pronta": "pronto_trigo",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_tomate",
        "nome": "Tomate",
        "preco_compra": 100,
        "preco_venda": 165,
        "tempo_colheita_horas": 6,
        "xp": 1,
        "nivel_requerido": 10,
        "img": "semente_tomate",
        "img_pronta": "pronto_tomate",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_framboesa",
        "nome": "Framboesa",
        "preco_compra": 190,
        "preco_venda": 475,
        "tempo_colheita_horas": 48,
        "xp": 2,
        "nivel_requerido": 11,
        "img": "semente_framboesa",
        "img_pronta": "pronto_framboesa",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_morango",
        "nome": "Morango",
        "preco_compra": 100,
        "preco_venda": 175,
        "tempo_colheita_horas": 4,
        "xp": 1,
        "nivel_requerido": 12,
        "img": "semente_morango",
        "img_pronta": "pronto_morango",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_batata",
        "nome": "Batata",
        "preco_compra": 260,
        "preco_venda": 175,
        "tempo_colheita_horas": 4,
        "xp": 1,
        "nivel_requerido": 13,
        "img": "semente_batata_inglesa",
        "img_pronta": "pronto_batata_inglesa",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_algodao",
        "nome": "Algodão",
        "preco_compra": 170,
        "preco_venda": 538,
        "tempo_colheita_horas": 0.20,
        "xp": 2,
        "nivel_requerido": 14,
        "img": "semente_algodao",
        "img_pronta": "pronto_algodao",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_aloe_vera",
        "nome": "Aloe vera",
        "preco_compra": 200,
        "preco_venda": 349,
        "tempo_colheita_horas": 8,
        "xp": 1,
        "nivel_requerido": 15,
        "img": "semente_aloe_vera",
        "img_pronta": "pronto_aloe_vera",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_hortela",
        "nome": "Hortelã",
        "preco_compra": 250,
        "preco_venda": 510,
        "tempo_colheita_horas": 24,
        "xp": 2,
        "nivel_requerido": 16,
        "img": "semente_alcachofra",
        "img_pronta": "pronto_mirtilo",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_espinafre",
        "nome": "Espinafre",
        "preco_compra": 100,
        "preco_venda": 136,
        "tempo_colheita_horas": 0.0833,
        "xp": 1,
        "nivel_requerido": 16,
        "img": "semente_espinafre",
        "img_pronta": "pronto_espinafre",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_melancia",
        "nome": "Melancia",
        "preco_compra": 270,
        "preco_venda": 438,
        "tempo_colheita_horas": 72,
        "xp": 8,
        "nivel_requerido": 16,
        "img": "semente_melancia",
        "img_pronta": "pronto_melancia",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_girassol",
        "nome": "Girassol",
        "preco_compra": 125,
        "preco_venda": 315,
        "tempo_colheita_horas": 0.20,
        "xp": 2,
        "nivel_requerido": 17,
        "img": "semente_girassol",
        "img_pronta": "pronto_girassol",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    },
    {
        "id": "semente_cebola",
        "nome": "Cebola",
        "preco_compra": 170,
        "preco_venda": 275,
        "tempo_colheita_horas": 12,
        "xp": 1,
        "nivel_requerido": 19,
        "img": "semente_cebola",
        "img_pronta": "pronto_cebola",
        "tipo": "semente",
        "escala": 0.78,
        "area": [4, 4],
        "noStopBuy": false,
        "tipo_plantacao": "solo_plantado_simples"
    }
]

export const arvores = [

    {
        "id": "arvore_abrico",
        "nome": "Abricó",
        "preco_compra": 380,
        "preco_compra_grana": 0,
        "preco_venda": 25,
        "tempo_colheita_horas": 36,
        "xp": 2,
        "nivel_requerido": 5,
        "img": "cerejeira",
        "escala": 0.6,
        "area": [1, 1],
        "origem": [0.5, 0.75],
        "tipo": "arvore"
    },
    {
        "id": "arvore_maca",
        "nome": "Maçã",
        "preco_compra": 650,
        "preco_compra_grana": 0,
        "preco_venda": 55,
        "tempo_colheita_horas": 72,
        "xp": 3,
        "nivel_requerido": 5,
        "img": "macieira",
        "escala": 0.45,
        "area": [1, 1],
        "origem": [0.5, 0.85],
        "tipo": "arvore"
    },
    {
        "id": "arvore_atemoia",
        "nome": "Atemoia",
        "preco_compra": 600,
        "preco_compra_grana": 0,
        "preco_venda": 40,
        "tempo_colheita_horas": 48,
        "xp": 4,
        "nivel_requerido": 8,
        "img": "abrico",
        "escala": 0.4,
        "area": [1, 1],
        "origem": [0.5, 0.85],
        "tipo": "arvore",
        "noStopBuy": true
    },
    {
        "id": "arvore_pessego",
        "nome": "Pessego",
        "preco_compra": 420,
        "preco_compra_grana": 0,
        "preco_venda": 60,
        "tempo_colheita_horas": 48,
        "xp": 2,
        "nivel_requerido": 10,
        "tipo": "arvore",
        "nivel_requerido": 5,
        "img": "pessegueiro",
        "escala": 0.5,
        "area": [1, 1],
        "origem": [0.5, 0.75],
    },
    {
        "id": "arvore_nectarina",
        "nome": "Nectarina",
        "preco_compra": 600,
        "preco_compra_grana": 0,
        "preco_venda": 55,
        "tempo_colheita_horas": 72,
        "xp": 2,
        "nivel_requerido": 20,
        "tipo": "arvore",
        "img": "nectarina",
        "escala": 0.5,
        "area": [1, 1],
        "origem": [0.5, 0.82],
    }
]

export const animais = [
    {
        "id": "animal_vaca",
        "nome": "Vaca",
        "preco_compra": 600,
        "preco_compra_grana": 0,
        "preco_venda": 12,
        "tempo_colheita_horas": 0.2,
        "xp": 150,
        "nivel_requerido": 1,
        "img": "vaca",
        "escala": 0.30,
        "area": [2, 3],
        "tipo": "animal",
        "origem": [0.6, 0.6]
    },
    {
        "id": "animal_frango",
        "nome": "Frango",
        "preco_compra": 450,
        "preco_compra_grana": 0,
        "preco_venda": 20,
        "tempo_colheita_horas": 48,
        "xp": 100,
        "nivel_requerido": 4,
        "img": "galo",
        "escala": 0.15,
        "area": [1, 1],
        "origem": [0.4, 0.6],
        "tipo": "animal"
    },
    {
        "id": "animal_porco",
        "nome": "Porco",
        "preco_compra": 800,
        "preco_compra_grana": 0,
        "preco_venda": 40,
        "tempo_colheita_horas": 48,
        "xp": 200,
        "nivel_requerido": 10,
        "img": "porco",
        "escala": 0.20,
        "area": [2, 2],
        "tipo": "animal"
    },
    {
        "id": "animal_ovelha",
        "nome": "Ovelha",
        "preco_compra": 550,
        "preco_compra_grana": 0,
        "preco_venda": 30,
        "tempo_colheita_horas": 36,
        "xp": 150,
        "nivel_requerido": 7,
        "img": "ovelha",
        "escala": 0.25,
        "area": [1, 2],
        "origem": [0.6, 0.6],
        "tipo": "animal"
    }
]

export const decoracoes = [
    {
        "id": "boneco",
        "nome": "Boneco",
        "preco_compra": 0,
        "preco_compra_grana": 18,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 490,
        "nivel_requerido": 0,
        "img": "boneco_frente",
        "escala": 0.5,
        "area": [1, 1],
        "origem": [0.4, 0.8],
        "tipo": "decoracao"
    },
    {
        "id": "gazebo",
        "nome": "Gazebo",
        "preco_compra": 0,
        "preco_compra_grana": 18,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 490,
        "nivel_requerido": 0,
        "img": "bangalo",
        "escala": 1.1,
        "area": [3, 3],
        "origem": [0.5, 0.8],
        "tipo": "decoracao"
    },
    {
        "id": "cerca_branca",
        "nome": "Cerca branca",
        "tipo": "cerca",
        "preco_compra": 0,
        "preco_compra_grana": 18,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 490,
        "nivel_requerido": 0,
        "img": "cerca_branca",
        "escala": 0.4,
        "area": [5, 1],
        "origem": [0.5, 0.5],
        "noStopBuy": true,
    },
    {
        "id": "cabana_de_descanso",
        "nome": "Cabana de descanso",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 2,
        "tipo": "decoracao"
    },
    {
        "id": "cabana",
        "nome": "Cabana",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 4,
        "tipo": "decoracao"
    },
    {
        "id": "cabana_rosa",
        "nome": "Cabana rosa",
        "tipo": "cerca",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 4,
        "nivel_requerido": 10,
        "img": "cerca_madeira_CE_canto_inferior",
        "escala": 0.4,
        "area": [2, 4],
        "origem": [0.35, 0.7],
    },
    {
        "id": "cerca_de_madeira",
        "nome": "Cerca solta",
        "tipo": "cerca",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 4,
        "img": "cerca_madeira_unico",
        "escala": 0.6,
        "area": [5, 2],
        "origem": [0.55, 0.65],
        "origem_flip": [0.4, 0.65]
    },
    {
        "id": "poco",
        "nome": "Poço",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 4,
        "img": "toquinho",
        "escala": 0.6,
        "area": [5, 4],
        "origem": [0.5, 0.65],
        "tipo": "decoracao"

    },
    {
        "id": "oficina",
        "nome": "Oficina",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 15,
        "tipo": "decoracao"
    },
    {
        "id": "celeiro_vermelho",
        "nome": "Celeiro Vermelho",
        "preco_compra": 82000,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 410,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "celerio_rosa",
        "nome": "Celerio Rosa",
        "preco_compra": 0,
        "preco_compra_grana": 27,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 820,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "celeiro_preto",
        "nome": "Celeiro Preto",
        "preco_compra": 0,
        "preco_compra_grana": 27,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 820,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "celerio_azul",
        "nome": "Celerio Azul",
        "preco_compra": 0,
        "preco_compra_grana": 27,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 820,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "celeiro_branco",
        "nome": "Celeiro Branco",
        "preco_compra": 0,
        "preco_compra_grana": 27,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 820,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "celeiro",
        "nome": "Celeiro",
        "preco_compra": 0,
        "preco_compra_grana": 27,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 820,
        "nivel_requerido": 0,
        "img": "armazem",
        "escala": 0.9,
        "area": [6, 6],
        "origem": [0.5, 0.7],
        "tipo": "decoracao"

    },
    {
        "id": "celeiro_velho",
        "nome": "Celeiro Velho",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 3,
        "tipo": "decoracao"
    },
    {
        "id": "barracao_rosa",
        "nome": "Barracão Rosa",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 7,
        "tipo": "decoracao"
    },
    {
        "id": "silo_de_graos",
        "nome": "Silo de grãos",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 13,
        "tipo": "decoracao"
    },
    {
        "id": "moinho_de_vento",
        "nome": "Moinho de vento",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 22,
        "img": "moinho",
        "escala": 0.35,
        "area": [3, 3],
        "origem": [0.5, 0.85],
        "tipo": "decoracao"
    },
    {
        "id": "casa_da_fazenda",
        "nome": "Casa da fazenda",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 26,
        "tipo": "decoracao"
    },
    {
        "id": "casa_da_fazenda_azul",
        "nome": "Casa da fazenda Azul",
        "preco_compra": 0,
        "preco_compra_grana": 0,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 0,
        "nivel_requerido": 26,
        "tipo": "decoracao"
    },
    {
        "id": "pagoda",
        "nome": "Pagoda",
        "preco_compra": 0,
        "preco_compra_grana": 48,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 1500,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "casa_de_cha",
        "nome": "Casa de chá",
        "preco_compra": 0,
        "preco_compra_grana": 38,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 1000,
        "nivel_requerido": 0,
        "tipo": "decoracao"
    },
    {
        "id": "trator",
        "nome": "Trator",
        "preco_compra": 1,
        "preco_compra_grana": 38,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 1000,
        "nivel_requerido": 0,
        "img": "trator",
        "escala": 0.2,
        "area": [3, 4],
        "tipo": "decoracao"
    },
    {
        "id": "trator_azul",
        "nome": "Trator Azul",
        "preco_compra": 0,
        "preco_compra_grana": 38,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 1000,
        "nivel_requerido": 0,
        "img": "trator2",
        "escala": 0.4,
        "area": [3, 4],
        "tipo": "decoracao"
    },
    {
        "id": "trator_verde",
        "nome": "Trator Azul",
        "preco_compra": 0,
        "preco_compra_grana": 38,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 1000,
        "nivel_requerido": 0,
        "img": "trator3",
        "escala": 1.0,
        "area": [4, 4],
        "tipo": "decoracao"
    },
    {
        "id": "estabulo",
        "nome": "Estábulo",
        "preco_compra": 0,
        "preco_compra_grana": 38,
        "preco_venda": 0,
        "tempo_colheita_horas": 0,
        "xp": 1000,
        "nivel_requerido": 0,
        "img": "estabulo",
        "escala": 0.5,
        "area": [2, 5],
        "origem": [0.5, 0.65],
        "tipo": "decoracao"
    }

]

export const solos = [
    {
        "nome": "solo_preparado",
        "img": "solo.png",
        "escala": 0.73,
        "area": [4, 4],
        "origem": [0.5, 0.58],
        "tipo": "solo_preparado",
        "noStopBuy": false
    },
    {
        "nome": "solo_plantado_simples",
        "img": "solo_plantado_simples.png",
        "escala": 0.73,
        "area": [4, 4],
        "origem": [0.5, 0.58],
        "tipo": "solo_plantado_simples",
        "noStopBuy": false
    }
]